changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - renovate

  categories:
    - title: Breaking Changes
      labels:
        - breaking-change

    - title: Features
      labels:
        - enhancement
        - feature

    - title: Bug Fixes
      labels:
        - bug
        - fix

    - title: Infrastructure
      labels:
        - ci
        - infrastructure

    - title: Other Changes
      labels:
        - "*"
