# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  - name: Dev Server
    before: brew install hugo
    # From here: https://github.com/gitpod-io/template-hugo
    # Using 'http://localhost:1313' instead of '$(gp url 1313)' in order to see preview in local VS Code
    command: hugo server -D -F --baseURL http://localhost:1313 --liveReloadPort=443 --appendPort=false --bind=0.0.0.0

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1313
    onOpen: open-preview