baseURL: http://gatezh.com/
languageCode: en-us
title: gatezh.com
theme: tale
googleAnalytics: UA-30716629-2

author:
  name: Serge Gatezh

params:
  description: Believe. Create.
  css:
    - style.css
