[build]
publish = "public"
# Below is a workarounddfrom here https://github.com/gohugoio/hugo/issues/5745#issuecomment-614490225
# TODO: ingegrate theme into the main repo
command = "find . -name _gen -exec rm -rf {} + ; hugo --gc --minify"


[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
