// `Env` (with the ASSETS Fetcher binding) comes from the generated
// worker-configuration.d.ts — see tsconfig.json. Declaring it by hand here
// would shadow the generated type and silently drift from wrangler.jsonc.

// Cloudflare's asset router rewrites /404.html -> /404 (html_handling:
// auto-trailing-slash), and /404 then matches the asset and is served with a
// 200 — making the error page an indexable URL of its own, which Google files
// as a soft 404. Both spellings are intercepted and given a real status.
//
// This has to live in the Worker: neither a zone setting nor _headers can
// change a response status, and _redirects only issues 3xx.
const NOT_FOUND_PATHS = new Set(["/404", "/404.html"]);

// Plain-text mirrors meant for agents, not search engines. They stay crawlable
// (an agent may fetch them without negotiating) but are marked noindex —
// otherwise every page ships a full-text duplicate of itself at a second URL.
//
// `_headers` would normally be the place for this, but it does not apply to
// responses generated by Worker code, and wrangler.jsonc routes these paths
// through the Worker so the negotiation flow can run.
// https://developers.cloudflare.com/workers/static-assets/headers/
function isAgentText(pathname: string): boolean {
  return pathname.endsWith(".md") || pathname === "/llms.txt" || pathname === "/llms-full.txt";
}

// A path that addresses a page rather than a file, and therefore has a Markdown
// representation to negotiate. This is the single source of truth for both
// halves of the feature: whether to look for a Markdown sibling, and whether to
// advertise `Vary: Accept`. Deriving them separately let the two drift — the
// previous check tested the whole path for a dot, so `/posts/v1.2-release`
// would have been served Markdown with no Vary header.
function isPagePath(pathname: string): boolean {
  if (pathname.endsWith("/")) return true;
  return !pathname.slice(pathname.lastIndexOf("/") + 1).includes(".");
}

// RFC 9110 media-range parsing, rather than a substring test. Two things a
// substring test gets wrong: `text/markdown;q=0` explicitly means NOT
// acceptable, and any unrelated type that happens to contain the characters
// (`application/x-text/markdown-ish`) would match.
function acceptsMarkdown(accept: string): boolean {
  for (const range of accept.split(",")) {
    const [mediaType, ...parameters] = range.split(";").map((part) => part.trim());

    if (mediaType.toLowerCase() !== "text/markdown") continue;

    const q = parameters.find((p) => p.toLowerCase().startsWith("q="));
    if (!q) return true;

    const weight = Number.parseFloat(q.slice(2));
    return Number.isFinite(weight) && weight > 0;
  }

  return false;
}

// Scheme canonicalisation (http -> https) and HSTS are deliberately NOT handled
// here. They are Cloudflare zone settings — "Always Use HTTPS" and "HTTP Strict
// Transport Security", both under SSL/TLS -> Edge Certificates — and the docs
// explicitly recommend against performing the redirect at the origin, which is
// what a Worker redirect amounts to. See docs/seo.md for the current state.
// https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/
export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (NOT_FOUND_PATHS.has(url.pathname)) {
      // Fetch via /404 — asking ASSETS for /404.html just returns the redirect.
      const notFound = await env.ASSETS.fetch(new URL("/404", url.origin));
      return new Response(notFound.body, { status: 404, headers: notFound.headers });
    }

    const negotiable = isPagePath(url.pathname);
    const resolved = await resolve(request, env, url, negotiable);

    // Headers on a subrequest response are immutable — clone before mutating.
    const response = new Response(resolved.body, resolved);

    // Only on paths this Worker actually negotiates. On a static asset it would
    // needlessly fragment downstream caches by request Accept header.
    if (negotiable) response.headers.append("Vary", "Accept");

    if (isAgentText(url.pathname)) response.headers.set("X-Robots-Tag", "noindex");

    return response;
  },
} satisfies ExportedHandler<Env>;

async function resolve(
  request: Request,
  env: Env,
  url: URL,
  negotiable: boolean,
): Promise<Response> {
  const wantsMarkdown =
    negotiable &&
    (request.method === "GET" || request.method === "HEAD") &&
    acceptsMarkdown(request.headers.get("Accept") ?? "");

  if (wantsMarkdown) {
    // Built by mutating a copy of the request URL, never by resolving a string
    // against the origin: a pathname beginning with "//" is a scheme-relative
    // reference, so `new URL("//host/x", origin)` yields a URL on `host`. The
    // pathname setter cannot change the host.
    const mdUrl = new URL(url);
    mdUrl.pathname = url.pathname.endsWith("/")
      ? `${url.pathname}index.md`
      : `${url.pathname}/index.md`;

    const mdResponse = await env.ASSETS.fetch(mdUrl);

    if (mdResponse.ok) {
      const response = new Response(mdResponse.body, mdResponse);
      response.headers.set("Content-Type", "text/markdown; charset=utf-8");
      // The negotiated body mirrors the HTML page, same as a direct .md hit —
      // keep it out of the index either way.
      response.headers.set("X-Robots-Tag", "noindex");
      return response;
    }

    // A miss returns the full 404 page body (not_found_handling: 404-page).
    // Nothing reads it, so release it rather than leaving a dangling stream.
    await mdResponse.body?.cancel();
  }

  return env.ASSETS.fetch(request);
}
