// `Env` (with the ASSETS Fetcher binding) comes from the generated
// worker-configuration.d.ts — see tsconfig.json. Declaring it by hand here
// would shadow the generated type and silently drift from wrangler.jsonc.

// Cloudflare's asset router rewrites /404.html -> /404 (html_handling:
// auto-trailing-slash), and /404 then matches the asset and is served with a
// 200 — making the error page an indexable URL of its own, which Google files
// as a soft 404. Both spellings are intercepted and given a real status.
//
// This has to live in the Worker: neither a zone setting nor _headers can
// change a response status, and _redirects only issues 3xx.
const NOT_FOUND_PATHS = new Set(["/404", "/404.html"]);

// Plain-text mirrors meant for agents, not search engines. They stay crawlable
// (an agent may fetch them without negotiating) but are marked noindex —
// otherwise every page ships a full-text duplicate of itself at a second URL.
//
// Normally an `_headers` file in the assets directory is the canonical place
// for this, but it does not apply here: Cloudflare's docs note that custom
// headers in _headers are not applied to responses generated by Worker code,
// including when `assets.run_worker_first` is set (wrangler.jsonc sets it, so
// the negotiation flow can run). With that config the documented approach is to
// attach headers in the Worker script.
// https://developers.cloudflare.com/workers/static-assets/headers/
function isAgentText(pathname: string): boolean {
  return pathname.endsWith(".md") || pathname === "/llms.txt" || pathname === "/llms-full.txt";
}

// Scheme canonicalisation (http -> https) and HSTS are deliberately NOT handled
// here. They are Cloudflare zone settings — "Always Use HTTPS" and "HTTP Strict
// Transport Security", both under SSL/TLS -> Edge Certificates — and the docs
// explicitly recommend against performing the redirect at the origin, which is
// what a Worker redirect amounts to. See docs/seo.md for the current state.
// https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/
export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    const resolved = await resolve(request, env, url);

    // Headers on a subrequest response are immutable — clone before mutating.
    const response = new Response(resolved.body, resolved);

    // Vary: Accept only on content pages (extensionless or trailing-slash
    // paths) — adding it to static assets like /css/main.css would needlessly
    // fragment the CDN cache by request Accept header.
    if (url.pathname.endsWith("/") || !url.pathname.includes(".")) {
      response.headers.append("Vary", "Accept");
    }

    if (isAgentText(url.pathname)) {
      response.headers.set("X-Robots-Tag", "noindex");
    }

    return response;
  },
} satisfies ExportedHandler<Env>;

async function resolve(request: Request, env: Env, url: URL): Promise<Response> {
  if (NOT_FOUND_PATHS.has(url.pathname)) {
    // Fetch via /404 — asking ASSETS for /404.html just returns the redirect.
    const notFound = await env.ASSETS.fetch(new URL("/404", url.origin));
    return new Response(notFound.body, { status: 404, headers: notFound.headers });
  }

  const accept = request.headers.get("Accept") ?? "";

  if ((request.method === "GET" || request.method === "HEAD") && accept.includes("text/markdown")) {
    const mdPath = url.pathname.endsWith("/")
      ? `${url.pathname}index.md`
      : `${url.pathname}/index.md`;

    const mdResponse = await env.ASSETS.fetch(new URL(mdPath, url.origin));

    if (mdResponse.ok) {
      const response = new Response(mdResponse.body, mdResponse);
      response.headers.set("Content-Type", "text/markdown; charset=utf-8");
      // The negotiated body mirrors the HTML page, same as a direct .md hit —
      // keep it out of the index either way.
      response.headers.set("X-Robots-Tag", "noindex");
      return response;
    }
  }

  return env.ASSETS.fetch(request);
}
