// Generated by Wrangler
// After running `wrangler types`, this file will be auto-generated
// with the correct types for your Worker environment

interface Env {
  AIRTABLE_API_KEY: string;
  AIRTABLE_BASE_ID: string;
  AIRTABLE_TABLE_NAME: string;
  RESEND_API_KEY?: string;
  CONTACT_EMAIL_TO?: string;
  CONTACT_EMAIL_FROM?: string;
  ALLOWED_ORIGINS?: string;
}
